### ISSUE TITLE
how to install ?

### ISSUE THREAD

**Issue by arpit1997** [tualatrix/ubuntu-tweak#31]
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by aviaryan** [comment]
It looks like setuptools is not installed in your system.
To do that, first install pip
```
sudo apt-get install python-pip
```
Then install the setuptools module. (restarting terminal may be needed)
```
sudo pip install setuptools
```

**Comment by arpit1997** [comment]
thanks for your suggestion issue resolved
