### ISSUE TITLE
error in setup.cfg command 'build' has no such option 'i18n'

### ISSUE THREAD

**Issue by ismdcf** [tualatrix/ubuntu-tweak#34]
I get the following error when running on ubuntu 14.04

error in setup.cfg command 'build' has no such option 'i18n'

.

**Comment by ScaY** [comment]
You can resolve this issue by removing `i18n=True` and `icons=True` from the _setup.cfg_
But when I have some issue when I start `./ubuntu-tweak` (he's still loading)

**Comment by Hugo14453** [comment]
This is a duplicate of #6 , do 'sudo apt-get install python-distutils-extra' to fix. (worked on 16.04 anyway)

**Comment by ismdcf** [comment]
all right closing it

**Comment by bendevnull** [comment]
That fix doesn't work on 18.04. Is there any other possibility?

**Comment by Neil-Lunavat** [comment]
Its actually `python3-distutils-extra` now. (hope it helps)
