### ISSUE TITLE
error: error in setup.cfg: command 'build' has no such option 'i18n'

### ISSUE THREAD

**Issue by fantaxy025025** [tualatrix/ubuntu-tweak#6]
error: error in setup.cfg: command 'build' has no such option 'i18n'

this error.

**Comment by Neil-Lunavat** [comment]
> There are many environment dependencies and I spend 2 hours search and install them.

Thank you for spending two hours and sparing my time. :)

Edit: Its actually `python3-distutils-extra` now...
